import { defineConfig } from "oxlint";

export default defineConfig({
  ignorePatterns: ["dist", "coverage", "src/locales"],
  env: { browser: true },
  plugins: [
    "oxc",
    "typescript",
    "react",
    "react-perf",
    "import",
    "jsdoc",
    "jsx-a11y",
    "promise",
  ],
  jsPlugins: ["@e18e/eslint-plugin", "eslint-plugin-lingui"],
  options: { typeAware: true },
  rules: {
    "e18e/prefer-array-at": "error",
    "e18e/prefer-array-fill": "error",
    "e18e/prefer-includes": "error",
    "e18e/prefer-array-to-reversed": "error",
    "e18e/prefer-array-to-sorted": "error",
    "e18e/prefer-array-to-spliced": "error",
    "e18e/prefer-nullish-coalescing": "error",
    "e18e/prefer-object-has-own": "error",
    "e18e/prefer-spread-syntax": "error",
    "e18e/prefer-url-canparse": "error",
    "e18e/ban-dependencies": "error",
    "e18e/prefer-array-from-map": "error",
    "e18e/prefer-timer-args": "error",
    "e18e/prefer-date-now": "error",
    "e18e/prefer-regex-test": "error",
    "e18e/prefer-array-some": "error",
    "e18e/prefer-static-regex": "error",
    "e18e/prefer-string-fromcharcode": "error",
    "react/exhaustive-deps": "warn",
    "react/rules-of-hooks": "error",
    "react/react-compiler": "error",
    "react/only-export-components": [
      "error",
      {
        allowConstantExport: true,
      },
    ],
    "lingui/t-call-in-function": "error",
    "lingui/no-single-tag-to-translate": "warn",
    "lingui/no-single-variables-to-translate": "warn",
    "lingui/no-trans-inside-trans": "warn",
    "lingui/no-expression-in-message": "warn",
  },
});
