---
name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js LTS/Jod
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Lint project
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test

  lighthouse:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js LTS/Jod
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Start server
        run: |
          pnpm run build
          pnpm run preview &
          sleep 5

      - name: Run Lighthouse 12
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: http://localhost:4173
          uploadArtifacts: true
          temporaryPublicStorage: true
