---
name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

permissions: {}

jobs:
  copilot-setup-steps:
    name: "Copilot Setup Steps"
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      VITE_DISABLE_VERCEL_ANALYTICS: "true"

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install PNPM
        uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2.0.2
        with:
          version: 12
